server:
  port: 8082
  servlet:
    context-path: /api
logging:
  level:
    root: info
    cn.yiyang: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_02?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  redis:
    host: 192.168.6.4
    port: 6379
    password:


#自定义配置信息@Value("${cn.wang.name/age}}")进行获取
cn:
  wang:
    name: 王一扬
    age: 26
